spring:
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5492}/${db.name:dmi_poc}?useSSL=false
    username: ${db.uid:postgres}
    password: ${db.pwd:lonewolf}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


app:
  minio:
    host: http://localhost:9000
    accessKey: rbt6CNmVEl1UiaAS6viB
    secretKey: Q9jbat71jYHv1ySgjay7Mfyp01tV0c9lYYIXCa6d
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
  configuration:
    uploadProvider: local

logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: INFO

debug: false


